# Generated by Django 4.1.1 on 2022-09-14 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='Sin nombres', max_length=200, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=12, unique=True, verbose_name='Dni')),
                ('date_joind', models.DateField(default=datetime.datetime.now, verbose_name='Fecha registro')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Fecha crear')),
                ('date_update', models.DateTimeField(auto_now_add=True, verbose_name='Fecha actualizar')),
                ('age', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('status', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%M/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%M/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleado',
                'db_table': 'Empleado',
                'ordering': ['id'],
            },
        ),
    ]
