# Generated by Django 4.1.1 on 2022-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_empleado_table_alter_type_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombres', max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
                'db_table': 'Categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelTable(
            name='type',
            table='Tipos',
        ),
        migrations.AddField(
            model_name='empleado',
            name='categ',
            field=models.ManyToManyField(to='erp.categoria'),
        ),
    ]
