# Generated by Django 4.1.1 on 2022-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_categoria_alter_type_table_empleado_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='Sin nombres', max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
